name = "hugo-theme-terminal"
license = "MIT"
licenselink = "https://github.com/jettdc/hugo-theme-terminal/blob/master/LICENSE"
description = " minimal and responsive Hugo theme inspired by the system console, crafted for optimal performance with an average page load time of under one second."
homepage = "https://github.com/jettdc/hugo-theme-terminal"
tags = ["blog", "gallery", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro", "animation"]
features = ["disqus", "responsive", "google analytics"]
min_version = "0.90.0"

[author]
  name = "Marcin Mierzejewski"
  homepage = "https://jettdc.com"
  github = "https://github.com/jettdc"

[original]
  author = "Jonas D."
  homepage = "https://terminalcss.xyz/"
  repo = "https://github.com/Gioni06/terminal.css"
